global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'name']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - send_resolved: True
    url: http://localhost:8080/alert
