global:
  scrape_interval:     10s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:8080']
    labels:
      team: bizaccount
rule_files:
- "alert.rules"
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:9093"
