global:
  scrape_interval:     10s
  evaluation_interval: 15s
scrape_configs:
- job_name: services
  static_configs:
  - targets: ['localhost:8080']
- job_name: feed
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
  - targets: ['51.15.78.223:88']
rule_files:
- "alert.rules"
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:9093"
